feat(mudl): create new directory each time for download to happen in
This way each invocation of the script can run 'parallel' to all the
other invocations because everything is contained within separate
temporary directories.

Although this seems like a hacky way to do it, it seems to be a much
better way than the way the mdl script currently works, which is to
parse different lines of the same files as different downloads (which
obviously brings in a lot of edge cases and is therefore much harder to
manage).

Perhaps there is a better way to do this though...

diff --git a/bin/mudl b/bin/mudl
--- a/bin/mudl
+++ b/bin/mudl
@@ -7,10 +7,18 @@
 # - mpd and mpc (optional)
 
 dl_dir="$HOME/dl/music"
+tmp_dir_name='tmp'
+tmp_n=1
 
 if [[ ! -d $dl_dir ]]; then
   read -p "Download directory '$dl_dir' does not exist, create it? (y/N)" \
        createp
-  [[ "${createp}" == "y" ]] && mkdir -pv $dl_dur || echo 'Aborting download' \
+  [[ "${createp}" == "y" ]] && mkdir -pv $dl_dur || echo 'Aborting download.' \
                                                          && exit 1
 fi
+
+while [[ -d "${dl_dir}/${tmp_dir_name}$tmp_n" ]]; do
+  tmp_n=$(($tmp_n + 1))
+done
+
+mkdir -pv "${dl_dir}/${tmp_dir_name}$tmp_n"
